name = "my-app"
compatibility_date = "2023-12-01"
node_compat = true
# [vars]
# MY_VAR = "my-variable"
[vars]
DATABASE_URL=""
JWT_SECRET=""
 
 
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

 

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"  